version: "3.9"

services:
  api:
    image: maharanasunil1843/api-exercise:02
    container_name: api
    ports:
      - "8080:3030"
    environment:
      - PORT=3030
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=predictions
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=predictions
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge